services:
  mysql:
      env_file:
        - mysql.env
      build:
        context: .
        dockerfile: mysql.Dockerfile
      container_name: mysql
      restart: unless-stopped
      volumes:
        - ./data/mysql:/var/lib/mysql
      ports:
        - "127.0.0.1:3307:3306"  # Bind only to localhost for security
      networks:
        localnetwork:
  mysql-backoffice-db:
      env_file:
        - mysql.env
      environment:
        MYSQL_DATABASE: backoffice
        MYSQL_USER: backoffice_user
      build:
        context: .
        dockerfile: mysql.Dockerfile
      container_name:  mysql-backoffice-db
      restart: unless-stopped
      volumes:
        - ./data/mysql-backoffice:/var/lib/mysql
      ports:
        - "127.0.0.1:3308:3306"  # Bind only to localhost for security
      networks:
        localnetwork:
  backoffice_elasticsearch:
    container_name: backoffice-elasticsearch-local
    image: 'elasticsearch:6.8.4'
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9300:9300"
      - "9200:9200"
    networks:
      localnetwork:
    environment:
      - discovery.type=single-node

networks:
  localnetwork:
    driver: bridge
