services:
  mysql:
      env_file:
        - mysql.env
      build:
        context: .
        dockerfile: mysql.Dockerfile
      container_name: mysql-test-db
      restart: unless-stopped
      volumes:
        - ./data-test/mysql:/var/lib/mysql
      ports:
        - "127.0.0.1:3307:3306"  # Bind only to localhost for security
      networks:
        testnetwork:

networks:
  testnetwork:
    driver: bridge
